In [1]:
import numpy as np

In [2]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [3]:
np.array([10, 20, 30])

array([10, 20, 30])

### zeros

In [6]:
a = np.zeros((3,5,5))

In [7]:
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
a.ndim

3

In [9]:
a.size

75

In [11]:
a.shape

(3, 5, 5)

### ones

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((3, 4, 5))

# 3 arrays with 4 rows and 5 columns

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## broadcasting

In [19]:
numpy1 = np.arange(10, 20)

In [22]:
a = numpy1.reshape(2,5)

In [23]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
numpy2 = np.arange(20, 30)

In [25]:
a1 = numpy2.reshape(2,5)

In [26]:
a1

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [27]:
arr_br = a + a1

In [28]:
arr_br

array([[30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

### linspace

In [29]:
np.linspace(2, 5, num=6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [31]:
np.linspace(1000, 1000000, num=10)

array([   1000.,  112000.,  223000.,  334000.,  445000.,  556000.,
        667000.,  778000.,  889000., 1000000.])

In [34]:
np.linspace(3, 10, 10).reshape(5,2)

array([[ 3.        ,  3.77777778],
       [ 4.55555556,  5.33333333],
       [ 6.11111111,  6.88888889],
       [ 7.66666667,  8.44444444],
       [ 9.22222222, 10.        ]])

### using endpoints

If we endpoints to false, it remove some decimal points from end

In [39]:
np.linspace(6, 19, 20, endpoint=False).reshape(4,5)

array([[ 6.  ,  6.65,  7.3 ,  7.95,  8.6 ],
       [ 9.25,  9.9 , 10.55, 11.2 , 11.85],
       [12.5 , 13.15, 13.8 , 14.45, 15.1 ],
       [15.75, 16.4 , 17.05, 17.7 , 18.35]])

## logspace

Return numbers spaced evenly on a log scale.

In [40]:
np.logspace(1, 50, 50, endpoint=False)

array([1.00000000e+01, 9.54992586e+01, 9.12010839e+02, 8.70963590e+03,
       8.31763771e+04, 7.94328235e+05, 7.58577575e+06, 7.24435960e+07,
       6.91830971e+08, 6.60693448e+09, 6.30957344e+10, 6.02559586e+11,
       5.75439937e+12, 5.49540874e+13, 5.24807460e+14, 5.01187234e+15,
       4.78630092e+16, 4.57088190e+17, 4.36515832e+18, 4.16869383e+19,
       3.98107171e+20, 3.80189396e+21, 3.63078055e+22, 3.46736850e+23,
       3.31131121e+24, 3.16227766e+25, 3.01995172e+26, 2.88403150e+27,
       2.75422870e+28, 2.63026799e+29, 2.51188643e+30, 2.39883292e+31,
       2.29086765e+32, 2.18776162e+33, 2.08929613e+34, 1.99526231e+35,
       1.90546072e+36, 1.81970086e+37, 1.73780083e+38, 1.65958691e+39,
       1.58489319e+40, 1.51356125e+41, 1.44543977e+42, 1.38038426e+43,
       1.31825674e+44, 1.25892541e+45, 1.20226443e+46, 1.14815362e+47,
       1.09647820e+48, 1.04712855e+49])

### broadcasting

In [48]:
a1 = np.arange(10, 26)

In [51]:
num1 = a1.reshape(4,4)

In [44]:
a2 = np.arange(20, 30)

In [52]:
num2 = a2.reshape(5,2)

In [54]:
num1 + num2

ValueError: operands could not be broadcast together with shapes (4,4) (5,2) 

### Convert 1D to 2D array

In [55]:
arr1 = np.array([1, 11, 33, 44, 66, 100])
arr1

array([  1,  11,  33,  44,  66, 100])

In [56]:
arr1.ndim

1

In [58]:
arr2 = arr1.reshape(1, -1)

In [59]:
arr2

array([[  1,  11,  33,  44,  66, 100]])

In [60]:
arr2.ndim

2

## copy array

In [61]:
x = np.array([6, 10 ,103, 101])
x

array([  6,  10, 103, 101])

In [69]:
# copy the array using np.copy method

In [62]:
y = x.copy()

In [63]:
y

array([  6,  10, 103, 101])

In [65]:
x[2] = 105

In [66]:
x

array([  6,  10, 105, 101])

In [77]:
y

array([  6,  10, 103, 101])

**Summary:**

if we use np.copy() method for copying an array, then if we update an array, 
that change is not also reflected on another array.

### copy the array using assignment ooperator

In [70]:
x

array([  6,  10, 105, 101])

In [71]:
z = x

In [72]:
z

array([  6,  10, 105, 101])

In [74]:
x[2] = 20

In [75]:
x

array([  6,  10,  20, 101])

In [76]:
z

array([  6,  10,  20, 101])

**Summary:**

if we use assignment operator for copying an array, then if we update an array, 
that change is also reflected on another array aw well. 

## id method

In [81]:
z = np.array([6, 10 ,30 ,1001, 303])

In [82]:
z

array([   6,   10,   30, 1001,  303])

In [83]:
id(z[2])

140163594306672

In [84]:
id(z[4])

140163580780976

In [85]:
id(z[2]) == id(z[4])

True