In [1]:
import numpy as np

In [5]:
a = np.array([7,8,9,10])

In [6]:
a

array([ 7,  8,  9, 10])

In [7]:
a[1:3]

array([8, 9])

In [8]:
a.shape

(4,)

In [9]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr1.ndim

2

### 3D Array

In [13]:
g = np.array([
    [[1,2,3], [7,8,0], [10,11,23]]
])

In [14]:
g

array([[[ 1,  2,  3],
        [ 7,  8,  0],
        [10, 11, 23]]])

In [15]:
g.dtype

dtype('int64')

In [16]:
g.ndim

3

In [18]:
g[0][1]

array([7, 8, 0])

In [20]:
g[0][2]

array([10, 11, 23])

In [21]:
g.size

9

### using np.zeros

In [23]:
g = np.zeros(5)
g

array([0., 0., 0., 0., 0.])

### Convert the input to an ndarray

In [24]:
np.asanyarray([7,8,9,10])

array([ 7,  8,  9, 10])

### Interpret the input as a matrix.

In [25]:
np.mat([7,18,19,20])

matrix([[ 7, 18, 19, 20]])

### np.arange()

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### using np.linspace

Create an array of value with in given range.

In [28]:
np.linspace(10, 40, 5)

array([10. , 17.5, 25. , 32.5, 40. ])

### using fromfunction

In [29]:
np.fromfunction(lambda x,y: x+y, (5,5), dtype=int)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [31]:
a = np.fromfunction(lambda x,y,z: x*y*z, (3,3,2), dtype=int)

(3,3,2) means 3 matrixes, 3 rows and 2 columns

In [32]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [33]:
a.ndim

3

In [34]:
a.size

18

In [35]:
a.dtype

dtype('int64')

In [36]:
a.shape

(3, 3, 2)

### astype function

In [37]:
arr_1 = np.array([4,5,7,10.7, 1,8])

In [38]:
arr_1

array([ 4. ,  5. ,  7. , 10.7,  1. ,  8. ])

In [39]:
arr_1.dtype

dtype('float64')

#### Convert int64 type to float64 type

In [43]:
arr_float_1 = arr_1.astype(dtype=np.int64)
arr_float_1

array([ 4,  5,  7, 10,  1,  8])

In [42]:
arr_float_1.dtype

dtype('int64')

In [44]:
aar_2 = np.array(['55', '66', '77', '88'])
aar_2

array(['55', '66', '77', '88'], dtype='<U2')

In [47]:
aa2_final = aar_2.astype(dtype=np.int64)

In [48]:
aa2_final

array([55, 66, 77, 88])

In [49]:
aa2_final.dtype

dtype('int64')

## Other Numpy Functions

In [50]:
np.random.randint(2, 10, 6)

array([6, 7, 9, 3, 2, 4])

In [51]:
arr1 = np.arange(10, 20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
arr1.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
np.random.random_sample(40)

array([0.53438524, 0.50831689, 0.26654534, 0.9841185 , 0.33800398,
       0.99575055, 0.69487488, 0.23358703, 0.91288505, 0.70542314,
       0.69866773, 0.67547043, 0.04596933, 0.67702966, 0.56422724,
       0.13197004, 0.23209726, 0.94761356, 0.70243637, 0.7064088 ,
       0.00525933, 0.27836407, 0.79669128, 0.00333729, 0.30009613,
       0.18460537, 0.65332582, 0.58378334, 0.73614438, 0.95173549,
       0.1962507 , 0.71662415, 0.21465562, 0.40078417, 0.81132503,
       0.28192306, 0.87245926, 0.28870398, 0.80310152, 0.70015264])

In [55]:
np.random.choice([6,7,10,11], 10)

array([11, 10, 11, 10,  6,  6,  7,  6,  7,  7])

In [56]:
np.random.randn()

-0.24817126278498672

### Transpose the matrix

In [59]:
arr1=np.arange(10, 30).reshape(4,5)

In [60]:
arr1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:
arr1.transpose()

array([[10, 15, 20, 25],
       [11, 16, 21, 26],
       [12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29]])

In [62]:
arr2 = np.arange(20, 50).reshape(5,6)

In [63]:
arr2

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [65]:
arr2.T

array([[20, 26, 32, 38, 44],
       [21, 27, 33, 39, 45],
       [22, 28, 34, 40, 46],
       [23, 29, 35, 41, 47],
       [24, 30, 36, 42, 48],
       [25, 31, 37, 43, 49]])

## Flattening an array

In [66]:
arr3 = np.arange(4, 40).reshape(9,4)
arr3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [67]:
arr3.shape

(9, 4)

In [68]:
arr3.size

36

In [69]:
arr3.ndim

2

In [71]:
arr3.flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [72]:
arr3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [75]:
### get values > 10

In [76]:
arr3[arr3 > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [77]:
arr2 = np.random.rand(8,5)

In [78]:
arr2

array([[0.10647648, 0.2690507 , 0.2642511 , 0.49570253, 0.25756635],
       [0.96213299, 0.05581238, 0.59631949, 0.29374018, 0.09387121],
       [0.39367805, 0.33303146, 0.51767316, 0.92472317, 0.06593142],
       [0.00245714, 0.82370584, 0.70120988, 0.2460711 , 0.29196237],
       [0.76739108, 0.10931595, 0.47051326, 0.65215476, 0.6200477 ],
       [0.72443065, 0.45932889, 0.38374921, 0.74552594, 0.279267  ],
       [0.41818225, 0.27769694, 0.40143067, 0.17681617, 0.9499612 ],
       [0.46146046, 0.11237053, 0.5471427 , 0.46820133, 0.67430488]])

In [81]:
arr2[1:8, 0:3]

array([[0.96213299, 0.05581238, 0.59631949],
       [0.39367805, 0.33303146, 0.51767316],
       [0.00245714, 0.82370584, 0.70120988],
       [0.76739108, 0.10931595, 0.47051326],
       [0.72443065, 0.45932889, 0.38374921],
       [0.41818225, 0.27769694, 0.40143067],
       [0.46146046, 0.11237053, 0.5471427 ]])

## numpy arithmetic operations

In [82]:
a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2 = np.array([[2,4,5], [0,9,0], [1,11,7]])

In [83]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
a2

array([[ 2,  4,  5],
       [ 0,  9,  0],
       [ 1, 11,  7]])

In [85]:
a2.ndim

2

In [86]:
a2.shape

(3, 3)

In [87]:
np.dot(a1, a2) # method 1

array([[  5,  55,  26],
       [ 14, 127,  62],
       [ 23, 199,  98]])

In [88]:
a1 @ a2 # method 2

array([[  5,  55,  26],
       [ 14, 127,  62],
       [ 23, 199,  98]])

### Example - 2 

In [94]:
a3 = np.array([[3,4], [9,0]])
a4 = np.array([[12,2], [3,7]])

In [95]:
a3

array([[3, 4],
       [9, 0]])

In [96]:
a4

array([[12,  2],
       [ 3,  7]])

In [97]:
a3 @ a4

array([[ 48,  34],
       [108,  18]])

In [98]:
np.dot(a3, a4)

array([[ 48,  34],
       [108,  18]])